package com.javampire.openscad.editor;

import com.intellij.openapi.Disposable;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.actionSystem.ActionManager;
import com.intellij.openapi.actionSystem.ActionPlaces;
import com.intellij.openapi.actionSystem.ActionToolbar;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.actionSystem.DataSink;
import com.intellij.openapi.actionSystem.DefaultActionGroup;
import com.intellij.openapi.actionSystem.Separator;
import com.intellij.openapi.actionSystem.UiDataProvider;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.application.ModalityState;
import com.intellij.openapi.application.ReadAction;
import com.intellij.openapi.application.WriteAction;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.fileEditor.*;
import com.intellij.openapi.fileEditor.impl.EditorHistoryManager;
import com.intellij.openapi.project.Project;
import com.intellij.psi.PsiDocumentManager;
import com.intellij.openapi.util.Disposer;
import com.intellij.openapi.util.UserDataHolderBase;
import com.intellij.openapi.vfs.VfsUtilCore;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.vfs.VirtualFileManager;
import com.intellij.openapi.vfs.newvfs.BulkFileListener;
import com.intellij.openapi.vfs.newvfs.events.VFileContentChangeEvent;
import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiManager;
import com.intellij.ui.JBColor;
import com.intellij.ui.jcef.JCEFHtmlPanel;
import com.intellij.util.Alarm;
import com.intellij.util.ui.components.BorderLayoutPanel;
import com.javampire.openscad.action.PreviewBackgroundActionGroup;
import com.javampire.openscad.action.*;
import org.cef.browser.CefBrowser;
import org.cef.browser.CefFrame;
import org.cef.browser.CefMessageRouter;
import org.cef.callback.CefQueryCallback;
import org.cef.handler.CefLoadHandlerAdapter;
import org.cef.handler.CefMessageRouterHandlerAdapter;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.HierarchyEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.List;

import static com.intellij.openapi.fileEditor.TextEditorWithPreview.Layout.SHOW_EDITOR;

/**
 * Preview editor. Right side of the {@link TextEditorWithPreview} generated by {@link OpenSCADTextEditorWithPreviewProvider}.
 * Display the preview file (= exported model in STL or 3MF format) in an HTML page through a {@link JCEFHtmlPanel}.
 */
public class OpenSCADPreviewFileEditor extends UserDataHolderBase implements FileEditor {
    private static final Logger LOG = Logger.getInstance(OpenSCADPreviewFileEditor.class);
    private final Project project;
    private final VirtualFile scadFile;
    private @Nullable OpenSCADPreviewSite previewSite;
    private final MainPanel mainPanel;
    private @Nullable JCEFHtmlPanel htmlPanel;
    private ActionToolbar previewToolbar;
    private final Alarm mySwingAlarm = new Alarm(Alarm.ThreadToUse.SWING_THREAD, this);
    private final Alarm previewRefreshAlarm = new Alarm(Alarm.ThreadToUse.SWING_THREAD, this);
    private @Nullable Disposable vfsListenerDisposable;
    /** Set when a save arrives before JCEF is attached; consumed on next render. */
    private boolean pendingRefreshOnSave;

    private OpenSCADPreviewFileEditorConfiguration editorConfig = new OpenSCADPreviewFileEditorConfiguration(this);

    public JCEFHtmlPanel getHtmlPanel() {
        return htmlPanel;
    }

    public OpenSCADPreviewFileEditor(@NotNull final Project project, @NotNull final VirtualFile scadFile) {
        this.project = project;
        this.scadFile = scadFile;
        this.mainPanel = new MainPanel();
        this.mainPanel.addHierarchyListener(e -> {
            if ((e.getChangeFlags() & HierarchyEvent.SHOWING_CHANGED) != 0 && mainPanel.isShowing()) {
                scheduleAttachHtmlPanel();
                scheduleRefreshIfAttached();
            }
        });
        this.mainPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                scheduleAttachHtmlPanel();
                scheduleRefreshIfAttached();
            }

            @Override
            public void componentHidden(ComponentEvent e) {
                mySwingAlarm.addRequest(
                        () -> detachHtmlPanel(),
                        0,
                        ModalityState.stateForComponent(getComponent())
                );
            }
        });
        ApplicationManager.getApplication().invokeLater(
                this::scheduleAttachHtmlPanel,
                ModalityState.stateForComponent(mainPanel)
        );
        registerSaveListener();
    }

    private void scheduleAttachHtmlPanel() {
        mySwingAlarm.addRequest(
                () -> attachHtmlPanel(),
                0,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void scheduleRefreshIfAttached() {
        mySwingAlarm.addRequest(
                () -> {
                    if (!Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
                        return;
                    }
                    if (pendingRefreshOnSave || htmlPanel == null) {
                        scheduleRefreshPreviewOnSave();
                    }
                    else {
                        refreshPreviewOnSave();
                    }
                },
                0,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void ensurePreviewSite() {
        if (previewSite == null) {
            previewSite = OpenSCADPreviewSiteFactory.getInstance(project).createSite(scadFile);
        }
    }

    public @Nullable OpenSCADPreviewSite getPreviewSite() {
        return previewSite;
    }

    public VirtualFile getFile() {
        return previewSite != null ? previewSite.htmlFile.getOriginalFile() : scadFile;
    }

    public OpenSCADPreviewFileEditorConfiguration getEditorConfig() {
        return editorConfig;
    }

    @Override
    public @NotNull JComponent getComponent() {
        return mainPanel;
    }

    @Override
    public @Nullable JComponent getPreferredFocusedComponent() {
        return mainPanel;
    }

    private static boolean isPreviewShown(@NotNull final Project project, @NotNull final VirtualFile file) {
        // Try and get historical layout for the file, only works when file has been opened in the past
        final OpenSCADTextEditorWithPreviewProvider provider = FileEditorProvider.EP_FILE_EDITOR_PROVIDER.findExtension(OpenSCADTextEditorWithPreviewProvider.class);
        if (provider != null) {
            final FileEditorState state = EditorHistoryManager.getInstance(project).getState(file, provider);
            if (state instanceof TextEditorWithPreview.MyFileEditorState) {
                return ((TextEditorWithPreview.MyFileEditorState) state).getSplitLayout() != SHOW_EDITOR;
            }
        }

        // No history for the file, getting the last known layout, whatever the file
        final String lastUsed = PropertiesComponent.getInstance().getValue("OpenSCADTextEditorWithPreviewLayout");
        // Layout ids match TextEditorWithPreview.Layout: "Editor only", "Preview only", "Editor and Preview"
        return lastUsed == null || !"Editor only".equals(lastUsed);
    }

    public Boolean isPreviewShown() {
        return isPreviewShown(project, scadFile);
    }

    private void attachHtmlPanel() {
        if (htmlPanel != null) {
            return;
        }
        ensurePreviewSite();
        if (previewSite == null) {
            showPreviewError("Preview site could not be created. Check the IDE log for details.");
            LOG.warn("OpenSCAD preview site was not created for " + scadFile.getPath());
            return;
        }
        if (previewSite.htmlFile == null) {
            showPreviewError("Preview HTML file could not be created. Check the IDE log for details.");
            LOG.warn("OpenSCAD preview HTML file was not created for " + scadFile.getPath());
            return;
        }
        htmlPanel = new JCEFHtmlPanel(true, null, previewSite.htmlFile.getPreviewUrl().toExternalForm());
        final CefMessageRouter messageRouter = CefMessageRouter.create();
        messageRouter.addHandler(new CefMessageRouterHandler(), true);
        htmlPanel.getJBCefClient().getCefClient().addMessageRouter(messageRouter);
        htmlPanel.getJBCefClient().addLoadHandler(new CefLoadHandlerAdapter() {
            @Override
            public void onLoadEnd(final CefBrowser browser, final CefFrame frame, final int httpStatusCode) {
                if (frame.isMain()) {
                    pendingRefreshOnSave = false;
                    renderWasmPreview();
                }
            }
        }, htmlPanel.getCefBrowser());
        previewToolbar = createToolbar(mainPanel);
        mainPanel.clearMessage();
        mainPanel.add(previewToolbar.getComponent(), BorderLayout.NORTH);
        mainPanel.add(htmlPanel.getComponent(), BorderLayout.CENTER);
        if (mainPanel.isShowing()) mainPanel.validate();
        mainPanel.repaint();
        htmlPanel.getCefBrowser().reload();
    }

    /**
     * Collect current editor sources and render them in the JCEF preview via WebAssembly.
     * Safe to call from any thread (including CEF load handlers).
     */
    public void renderWasmPreview() {
        if (htmlPanel == null) {
            return;
        }
        final CefBrowser browser = htmlPanel.getCefBrowser();
        final ModalityState modality = ModalityState.stateForComponent(getComponent());
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            final OpenSCADPreviewSourceCollector.PreviewSources sources = ReadAction.compute(
                    () -> {
                        commitDocumentIfOpen();
                        return OpenSCADPreviewSourceCollector.collect(project, scadFile);
                    }
            );
            ApplicationManager.getApplication().invokeLater(() -> {
                if (htmlPanel == null) {
                    return;
                }
                if (sources == null) {
                    showPreviewError("Could not read OpenSCAD sources for preview.");
                    LOG.warn("Failed to collect preview sources for " + scadFile.getPath());
                    return;
                }
                OpenSCADPreviewWasmBridge.render(browser, sources);
            }, modality);
        });
    }

    private void commitDocumentIfOpen() {
        final Document document = FileDocumentManager.getInstance().getDocument(scadFile);
        if (document != null) {
            PsiDocumentManager.getInstance(project).commitDocument(document);
        }
    }

    private void showPreviewError(@NotNull final String message) {
        mainPanel.showMessage(message);
    }

    private void detachHtmlPanel() {
        if (htmlPanel != null) {
            mainPanel.remove(previewToolbar.getComponent());
            previewToolbar = null;
            mainPanel.remove(htmlPanel.getComponent());
            Disposer.dispose(htmlPanel);
            htmlPanel = null;
        }
    }

    private ActionToolbar createToolbar(final JComponent targetComponent) {
        ActionToolbar actionToolbar = ActionManager.getInstance().createActionToolbar(
                ActionPlaces.EDITOR_TOOLBAR,
                new DefaultActionGroup(
                        new RefreshPreviewAction(),
                        new ToggleAutoRefreshAction(),
                        new Separator(),
                        new ToggleGridAction(),
                        new ToggleAxisAction(),
                        new PreviewBackgroundActionGroup(),
                        new SetModelColorAction(),
                        new Separator(),
                        new OpenAction(),
                        new ExportAction()
                ), true);
        actionToolbar.setTargetComponent(targetComponent);
        return actionToolbar;
    }

    private void registerSaveListener() {
        if (vfsListenerDisposable != null) {
            return;
        }
        vfsListenerDisposable = Disposer.newDisposable("OpenSCADPreviewSaveListener");
        // FileDocumentManagerListener is application-scoped; project bus does not receive save events.
        ApplicationManager.getApplication().getMessageBus().connect(vfsListenerDisposable)
                .subscribe(FileDocumentManagerListener.TOPIC, new FileDocumentManagerListener() {
                    @Override
                    public void afterDocumentSaved(@NotNull final Document document) {
                        final VirtualFile file = FileDocumentManager.getInstance().getFile(document);
                        if (file != null && isSameScadFile(file)) {
                            onScadFileSaved();
                        }
                    }
                });
        // l2trace99/openscad-plugin listens to all VFS content changes for the file (not only isFromSave).
        project.getMessageBus().connect(vfsListenerDisposable).subscribe(VirtualFileManager.VFS_CHANGES, new BulkFileListener() {
            @Override
            public void after(@NotNull final List<? extends VFileEvent> events) {
                for (final VFileEvent event : events) {
                    if (!(event instanceof VFileContentChangeEvent)) {
                        continue;
                    }
                    final VirtualFile file = event.getFile();
                    if (file != null && isSameScadFile(file)) {
                        onScadFileSaved();
                    }
                }
            }
        });
    }

    private boolean isSameScadFile(@NotNull final VirtualFile file) {
        return VfsUtilCore.pathEqualsTo(file, scadFile.getPath());
    }

    /**
     * Called when the main .scad file is saved or its VFS content changes.
     * Debounced; attaches JCEF if the preview pane is visible but not yet loaded.
     */
    private void onScadFileSaved() {
        if (!Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
            return;
        }
        ApplicationManager.getApplication().invokeLater(
                this::scheduleRefreshPreviewOnSave,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void scheduleRefreshPreviewOnSave() {
        if (!Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
            pendingRefreshOnSave = false;
            return;
        }
        pendingRefreshOnSave = true;
        if (mainPanel.isShowing()) {
            scheduleAttachHtmlPanel();
        }
        previewRefreshAlarm.cancelAllRequests();
        previewRefreshAlarm.addRequest(
                this::performScheduledRefreshOnSave,
                150,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void performScheduledRefreshOnSave() {
        if (!Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
            pendingRefreshOnSave = false;
            return;
        }
        if (htmlPanel == null) {
            if (mainPanel.isShowing()) {
                scheduleAttachHtmlPanel();
            }
            return;
        }
        pendingRefreshOnSave = false;
        refreshPreviewOnSave();
    }

    private void unregisterSaveListener() {
        if (vfsListenerDisposable != null) {
            Disposer.dispose(vfsListenerDisposable);
            vfsListenerDisposable = null;
        }
    }

    private void refreshPreviewOnSave() {
        editorConfig.saveConfiguration();
        renderWasmPreview();
    }

    @Override
    @Nls(capitalization = Nls.Capitalization.Title)
    @NotNull
    public String getName() {
        return OpenSCADPreviewFileEditor.class.getSimpleName();
    }

    @Override
    public void setState(@NotNull FileEditorState state) {
    }

    @Override
    public boolean isModified() {
        return false;
    }

    @Override
    public boolean isValid() {
        return true;
    }

    @Override
    public void addPropertyChangeListener(@NotNull PropertyChangeListener listener) {
    }

    @Override
    public void removePropertyChangeListener(@NotNull PropertyChangeListener listener) {
    }

    @Override
    public @Nullable FileEditorLocation getCurrentLocation() {
        return null;
    }

    @Override
    public void dispose() {
        unregisterSaveListener();
        detachHtmlPanel();
        final OpenSCADPreviewSite site = previewSite;
        if (site == null) {
            return;
        }
        ApplicationManager.getApplication().invokeLater(() -> WriteAction.run(() -> {
            try {
                if (site.previewFile != null) {
                    site.previewFile.delete(OpenSCADPreviewFileEditor.this);
                }
                if (site.htmlFile != null) {
                    site.htmlFile.getOriginalFile().delete(OpenSCADPreviewFileEditor.this);
                }
            }
            catch (final IOException ioe) {
                LOG.warn("An error occurred while deleting temporary scad preview files.", ioe);
            }
        }), ModalityState.nonModal());
    }

    private class MainPanel extends BorderLayoutPanel implements UiDataProvider {
        private final JLabel messageLabel = new JLabel("Loading preview...", SwingConstants.CENTER);

        MainPanel() {
            add(messageLabel, BorderLayout.CENTER);
        }

        void showMessage(@NotNull final String message) {
            messageLabel.setText("<html><center>" + message + "</center></html>");
            if (messageLabel.getParent() == null) {
                add(messageLabel, BorderLayout.CENTER);
            }
            revalidate();
            repaint();
        }

        void clearMessage() {
            remove(messageLabel);
        }

        @Override
        public void uiDataSnapshot(@NotNull final DataSink sink) {
            sink.set(OpenSCADDataKeys.PREVIEW_EDITOR, OpenSCADPreviewFileEditor.this);
            sink.set(CommonDataKeys.PROJECT, project);
            sink.set(CommonDataKeys.VIRTUAL_FILE, scadFile);
            sink.lazy(CommonDataKeys.PSI_FILE, () -> PsiManager.getInstance(project).findFile(scadFile));
        }
    }

    private class CefMessageRouterHandler extends CefMessageRouterHandlerAdapter {

        private final static String DELIMITER = "=";
        private final static String SHOW_AXIS = "showAxis";
        private final static String SHOW_GRID = "showGrid";
        private final static String MODEL_COLOR = "modelColor";
        private final static String PREVIEW_BACKGROUND = "previewBackground";
        private final static String PREVIEW_WARNING = "previewWarning";
        private final static String PREVIEW_ERROR = "previewError";

        @Override
        public boolean onQuery(CefBrowser browser, CefFrame frame, long queryId, String request, boolean persistent, CefQueryCallback callback) {
            final String[] parsed = request.split(DELIMITER, 2);
            if (SHOW_AXIS.equals(parsed[0])) {
                editorConfig.setShowAxis(Boolean.valueOf(parsed[1]));
            } else if (SHOW_GRID.equals(parsed[0])) {
                editorConfig.setShowGrid(Boolean.valueOf(parsed[1]));
            } else if (MODEL_COLOR.equals(parsed[0])) {
                editorConfig.setModelColor(JBColor.decode(parsed[1]));
            } else if (PREVIEW_BACKGROUND.equals(parsed[0])) {
                final PreviewBackground background = PreviewBackground.fromId(parsed[1]);
                if (background != null) {
                    editorConfig.syncPreviewBackgroundFromViewer(background);
                }
            } else if (PREVIEW_WARNING.equals(parsed[0])) {
                LOG.warn("OpenSCAD WASM preview: " + parsed[1]);
            } else if (PREVIEW_ERROR.equals(parsed[0])) {
                LOG.error("OpenSCAD WASM preview: " + parsed[1]);
            } else {
                LOG.info("Preview: " + request);
                callback.success("");
                return true;
            }
            callback.success("");
            return true;
        }
    }
}
