package com.javampire.openscad.editor;

import com.intellij.openapi.Disposable;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.actionSystem.ActionManager;
import com.intellij.openapi.actionSystem.ActionPlaces;
import com.intellij.openapi.actionSystem.ActionToolbar;
import com.intellij.openapi.actionSystem.ActionUiKind;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.actionSystem.DataContext;
import com.intellij.openapi.actionSystem.DataSink;
import com.intellij.openapi.actionSystem.DefaultActionGroup;
import com.intellij.openapi.actionSystem.Presentation;
import com.intellij.openapi.actionSystem.Separator;
import com.intellij.openapi.actionSystem.UiDataProvider;
import com.intellij.openapi.actionSystem.ex.ActionUtil;
import com.intellij.openapi.actionSystem.impl.SimpleDataContext;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.application.ModalityState;
import com.intellij.openapi.application.WriteAction;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.fileEditor.*;
import com.intellij.openapi.fileEditor.impl.EditorHistoryManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.Disposer;
import com.intellij.openapi.util.UserDataHolderBase;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.vfs.VirtualFileManager;
import com.intellij.openapi.vfs.newvfs.BulkFileListener;
import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiManager;
import com.intellij.ui.JBColor;
import com.intellij.ui.jcef.JCEFHtmlPanel;
import com.intellij.util.Alarm;
import com.intellij.util.ui.components.BorderLayoutPanel;
import com.javampire.openscad.action.*;
import org.cef.browser.CefBrowser;
import org.cef.browser.CefFrame;
import org.cef.browser.CefMessageRouter;
import org.cef.callback.CefQueryCallback;
import org.cef.handler.CefMessageRouterHandlerAdapter;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.HierarchyEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.List;

import static com.intellij.openapi.fileEditor.TextEditorWithPreview.Layout.SHOW_EDITOR;

/**
 * Preview editor. Right side of the {@link TextEditorWithPreview} generated by {@link OpenSCADTextEditorWithPreviewProvider}.
 * Display the preview file (= exported model in STL or 3MF format) in an HTML page through a {@link JCEFHtmlPanel}.
 */
public class OpenSCADPreviewFileEditor extends UserDataHolderBase implements FileEditor {
    private static final Logger LOG = Logger.getInstance(OpenSCADPreviewFileEditor.class);
    private final Project project;
    private final VirtualFile scadFile;
    private @Nullable OpenSCADPreviewSite previewSite;
    private final MainPanel mainPanel;
    private @Nullable JCEFHtmlPanel htmlPanel;
    private ActionToolbar previewToolbar;
    private final Alarm mySwingAlarm = new Alarm(Alarm.ThreadToUse.SWING_THREAD, this);
    private @Nullable Disposable vfsListenerDisposable;

    private OpenSCADPreviewFileEditorConfiguration editorConfig = new OpenSCADPreviewFileEditorConfiguration(this);

    public JCEFHtmlPanel getHtmlPanel() {
        return htmlPanel;
    }

    public OpenSCADPreviewFileEditor(@NotNull final Project project, @NotNull final VirtualFile scadFile) {
        this.project = project;
        this.scadFile = scadFile;
        this.mainPanel = new MainPanel();
        this.mainPanel.addHierarchyListener(e -> {
            if ((e.getChangeFlags() & HierarchyEvent.SHOWING_CHANGED) != 0 && mainPanel.isShowing()) {
                scheduleAttachHtmlPanel();
                scheduleRefreshIfAttached();
            }
        });
        this.mainPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                scheduleAttachHtmlPanel();
                scheduleRefreshIfAttached();
            }

            @Override
            public void componentHidden(ComponentEvent e) {
                mySwingAlarm.addRequest(
                        () -> detachHtmlPanel(),
                        0,
                        ModalityState.stateForComponent(getComponent())
                );
            }
        });
        ApplicationManager.getApplication().invokeLater(
                this::scheduleAttachHtmlPanel,
                ModalityState.stateForComponent(mainPanel)
        );
        registerSaveListener();
    }

    private void scheduleAttachHtmlPanel() {
        mySwingAlarm.addRequest(
                () -> attachHtmlPanel(),
                0,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void scheduleRefreshIfAttached() {
        if (htmlPanel == null) {
            return;
        }
        mySwingAlarm.addRequest(
                () -> {
                    if (htmlPanel != null && Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
                        refreshPreviewOnSave();
                    }
                },
                0,
                ModalityState.stateForComponent(getComponent())
        );
    }

    private void ensurePreviewSite() {
        if (previewSite == null) {
            previewSite = OpenSCADPreviewSiteFactory.getInstance(project).createSite(scadFile);
        }
    }

    public @Nullable OpenSCADPreviewSite getPreviewSite() {
        return previewSite;
    }

    public VirtualFile getFile() {
        return previewSite != null ? previewSite.htmlFile.getOriginalFile() : scadFile;
    }

    public OpenSCADPreviewFileEditorConfiguration getEditorConfig() {
        return editorConfig;
    }

    @Override
    public @NotNull JComponent getComponent() {
        return mainPanel;
    }

    @Override
    public @Nullable JComponent getPreferredFocusedComponent() {
        return mainPanel;
    }

    private static boolean isPreviewShown(@NotNull final Project project, @NotNull final VirtualFile file) {
        // Try and get historical layout for the file, only works when file has been opened in the past
        final OpenSCADTextEditorWithPreviewProvider provider = FileEditorProvider.EP_FILE_EDITOR_PROVIDER.findExtension(OpenSCADTextEditorWithPreviewProvider.class);
        if (provider != null) {
            final FileEditorState state = EditorHistoryManager.getInstance(project).getState(file, provider);
            if (state instanceof TextEditorWithPreview.MyFileEditorState) {
                return ((TextEditorWithPreview.MyFileEditorState) state).getSplitLayout() != SHOW_EDITOR;
            }
        }

        // No history for the file, getting the last known layout, whatever the file
        final String lastUsed = PropertiesComponent.getInstance().getValue("OpenSCADTextEditorWithPreviewLayout");
        // Layout ids match TextEditorWithPreview.Layout: "Editor only", "Preview only", "Editor and Preview"
        return lastUsed == null || !"Editor only".equals(lastUsed);
    }

    public Boolean isPreviewShown() {
        return isPreviewShown(project, scadFile);
    }

    private void attachHtmlPanel() {
        if (htmlPanel != null) {
            return;
        }
        ensurePreviewSite();
        if (previewSite == null) {
            showPreviewError("Preview site could not be created. Check the IDE log for details.");
            LOG.warn("OpenSCAD preview site was not created for " + scadFile.getPath());
            return;
        }
        if (previewSite.htmlFile == null) {
            showPreviewError("Preview HTML file could not be created. Check the IDE log for details.");
            LOG.warn("OpenSCAD preview HTML file was not created for " + scadFile.getPath());
            return;
        }
        htmlPanel = new JCEFHtmlPanel(true, null, previewSite.htmlFile.getPreviewUrl().toExternalForm());
        final CefMessageRouter messageRouter = CefMessageRouter.create();
        messageRouter.addHandler(new CefMessageRouterHandler(), true);
        htmlPanel.getJBCefClient().getCefClient().addMessageRouter(messageRouter);
        previewToolbar = createToolbar(mainPanel);
        mainPanel.clearMessage();
        mainPanel.add(previewToolbar.getComponent(), BorderLayout.NORTH);
        mainPanel.add(htmlPanel.getComponent(), BorderLayout.CENTER);
        if (mainPanel.isShowing()) mainPanel.validate();
        mainPanel.repaint();
        htmlPanel.getCefBrowser().reload();
        generatePreview();
    }

    private void showPreviewError(@NotNull final String message) {
        mainPanel.showMessage(message);
    }

    private void detachHtmlPanel() {
        if (htmlPanel != null) {
            mainPanel.remove(previewToolbar.getComponent());
            previewToolbar = null;
            mainPanel.remove(htmlPanel.getComponent());
            Disposer.dispose(htmlPanel);
            htmlPanel = null;
        }
    }

    private ActionToolbar createToolbar(final JComponent targetComponent) {
        ActionToolbar actionToolbar = ActionManager.getInstance().createActionToolbar(
                ActionPlaces.EDITOR_TOOLBAR,
                new DefaultActionGroup(
                        new RefreshPreviewAction(),
                        new ToggleAutoRefreshAction(),
                        new Separator(),
                        new ToggleGridAction(),
                        new ToggleAxisAction(),
                        new SetModelColorAction(),
                        new Separator(),
                        new OpenAction(),
                        new ExportAction()
                ), true);
        actionToolbar.setTargetComponent(targetComponent);
        return actionToolbar;
    }

    /**
     * Fake an action event to generate the preview.
     */
    private void generatePreview() {
        final AnAction generatePreviewAction = new GeneratePreviewAction();
        final DataContext dataContext = SimpleDataContext.builder()
                .add(OpenSCADDataKeys.PREVIEW_EDITOR, OpenSCADPreviewFileEditor.this)
                .build();
        final AnActionEvent event = AnActionEvent.createEvent(
                dataContext,
                new Presentation(GeneratePreviewAction.TEXT),
                ActionPlaces.UNKNOWN,
                ActionUiKind.NONE,
                null
        );
        ActionUtil.performAction(generatePreviewAction, event);
    }

    private void registerSaveListener() {
        if (vfsListenerDisposable != null) {
            return;
        }
        vfsListenerDisposable = Disposer.newDisposable("OpenSCADPreviewSaveListener");
        project.getMessageBus().connect(vfsListenerDisposable).subscribe(VirtualFileManager.VFS_CHANGES, new BulkFileListener() {
            @Override
            public void after(@NotNull final List<? extends VFileEvent> events) {
                for (final VFileEvent event : events) {
                    if (event.isFromSave() && scadFile.equals(event.getFile())
                            && Boolean.TRUE.equals(editorConfig.getAutoRefresh())) {
                        refreshPreviewOnSave();
                    }
                }
            }
        });
    }

    private void unregisterSaveListener() {
        if (vfsListenerDisposable != null) {
            Disposer.dispose(vfsListenerDisposable);
            vfsListenerDisposable = null;
        }
    }

    private void refreshPreviewOnSave() {
        final AnAction refreshPreviewAction = new RefreshPreviewAction();
        final DataContext dataContext = SimpleDataContext.builder()
                .add(OpenSCADDataKeys.PREVIEW_EDITOR, OpenSCADPreviewFileEditor.this)
                .add(CommonDataKeys.PROJECT, project)
                .add(CommonDataKeys.VIRTUAL_FILE, scadFile)
                .build();
        final AnActionEvent event = AnActionEvent.createEvent(
                dataContext,
                new Presentation(RefreshPreviewAction.TEXT),
                ActionPlaces.UNKNOWN,
                ActionUiKind.NONE,
                null
        );
        ActionUtil.performAction(refreshPreviewAction, event);
    }

    @Override
    @Nls(capitalization = Nls.Capitalization.Title)
    @NotNull
    public String getName() {
        return OpenSCADPreviewFileEditor.class.getSimpleName();
    }

    @Override
    public void setState(@NotNull FileEditorState state) {
    }

    @Override
    public boolean isModified() {
        return false;
    }

    @Override
    public boolean isValid() {
        return true;
    }

    @Override
    public void addPropertyChangeListener(@NotNull PropertyChangeListener listener) {
    }

    @Override
    public void removePropertyChangeListener(@NotNull PropertyChangeListener listener) {
    }

    @Override
    public @Nullable FileEditorLocation getCurrentLocation() {
        return null;
    }

    @Override
    public void dispose() {
        unregisterSaveListener();
        detachHtmlPanel();
        final OpenSCADPreviewSite site = previewSite;
        if (site == null) {
            return;
        }
        ApplicationManager.getApplication().invokeLater(() -> WriteAction.run(() -> {
            try {
                if (site.previewFile != null) {
                    site.previewFile.delete(OpenSCADPreviewFileEditor.this);
                }
                if (site.htmlFile != null) {
                    site.htmlFile.getOriginalFile().delete(OpenSCADPreviewFileEditor.this);
                }
            }
            catch (final IOException ioe) {
                LOG.warn("An error occurred while deleting temporary scad preview files.", ioe);
            }
        }), ModalityState.nonModal());
    }

    private class MainPanel extends BorderLayoutPanel implements UiDataProvider {
        private final JLabel messageLabel = new JLabel("Loading preview...", SwingConstants.CENTER);

        MainPanel() {
            add(messageLabel, BorderLayout.CENTER);
        }

        void showMessage(@NotNull final String message) {
            messageLabel.setText("<html><center>" + message + "</center></html>");
            if (messageLabel.getParent() == null) {
                add(messageLabel, BorderLayout.CENTER);
            }
            revalidate();
            repaint();
        }

        void clearMessage() {
            remove(messageLabel);
        }

        @Override
        public void uiDataSnapshot(@NotNull final DataSink sink) {
            sink.set(OpenSCADDataKeys.PREVIEW_EDITOR, OpenSCADPreviewFileEditor.this);
            sink.set(CommonDataKeys.PROJECT, project);
            sink.set(CommonDataKeys.VIRTUAL_FILE, scadFile);
            sink.lazy(CommonDataKeys.PSI_FILE, () -> PsiManager.getInstance(project).findFile(scadFile));
        }
    }

    private class CefMessageRouterHandler extends CefMessageRouterHandlerAdapter {

        private final static String DELIMITER = "=";
        private final static String SHOW_AXIS = "showAxis";
        private final static String SHOW_GRID = "showGrid";
        private final static String MODEL_COLOR = "modelColor";

        @Override
        public boolean onQuery(CefBrowser browser, CefFrame frame, long queryId, String request, boolean persistent, CefQueryCallback callback) {
            final String[] parsed = request.split(DELIMITER);
            if (SHOW_AXIS.equals(parsed[0])) {
                editorConfig.setShowAxis(Boolean.valueOf(parsed[1]));
            } else if (SHOW_GRID.equals(parsed[0])) {
                editorConfig.setShowGrid(Boolean.valueOf(parsed[1]));
            } else if (MODEL_COLOR.equals(parsed[0])) {
                editorConfig.setModelColor(JBColor.decode(parsed[1]));
            } else {
                return false;
            }
            return true;
        }
    }
}
