# Run tests, plugin verification, and build on push to master.
#
# Docs:
# - GitHub Actions: https://help.github.com/en/actions
##

name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Test, Verify, and Build Plugin
        run: ./gradlew test verifyPlugin buildPlugin
